- name: Power Off All the Virtual Machines 
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_host: "192.168.1.3"
    esxi_user: "root"
    esxi_password: "#####"
    vms_to_power_off:
      - windows-master

  tasks:
    - name: Power off specified VMs
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item }}"
        state: powered-off
      loop: "{{ vms_to_power_off }}"

