---
- name: Deploy RHEL 9.6 VM from ISO on ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    esxi_host: "192.168.1.3"
    esxi_user: "root"
    esxi_password: "#####"
    datacenter_name: "ha-datacenter"
    folder_path: "ha-datacenter/vm"
    new_vm_name: "rhel96-master"
    datastore_name: "datastore2"
    network_name: "VM Network"
    ip_address: "192.168.1.212"
    netmask: "255.255.255.0"
    gateway: "192.168.1.1"
    dns_servers:
      - "192.168.1.254"
      - "8.8.8.8"

  tasks:
    - name: Deploy RHEL 9.6 VM from ISO
      community.vmware.vmware_guest:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_path }}"
        name: "{{ new_vm_name }}"
        guest_id: "rhel9_64Guest"
        datastore: "{{ datastore_name }}"
        state: poweredon
        hardware:
          memory_mb: 4096
          num_cpus: 2
          version: latest
        disk:
          - size_gb: 40
            type: thin
            datastore: "{{ datastore_name }}"
        networks:
          - name: "{{ network_name }}"
            ip: "{{ ip_address }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            dns_servers: "{{ dns_servers }}"
        cdrom:
          - type: iso
            iso_path: "[{{ datastore_name }}] rhel-9.6-x86_64-dvd.iso"
            controller_type: ide
            controller_number: 0
            unit_number: 0
        wait_for_ip_address: no
      delegate_to: localhost
      register: vm_deploy

    - name: Display VM deployment result
      debug:
        var: vm_deploy.instance.hw_name

